name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
    - name: Use ACCESS_ID secret
        env:
          ACCESS_ID: ${{ secrets.ACCESS_ID }}
        run: echo "The ACCESS_ID is $ACCESS_ID"
